### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by sirthias** [TomSDEVSN/hetznercloud-java#1]
It'd be great if `hetznercloud-java` was available through maven central and thus did not require local building and publishing...

**Comment by TomSDEVSN** [comment]
Hi Mathias,

thank you for your issue.

So, you don't need to build it locally. I upload the artifacts on my Nexus server every time (see https://github.com/TomSDEVSN/hetznercloud-java/wiki/Initialize-the-integration-in-your-project).

Best Regards
Tom

**Comment by sirthias** [comment]
ok, I see.
Could you (also) publish to sonatype/maven central, so people don't have to add another artifact repository, which can slow down artifact resolution (because the build tools don't know, which artifacts exactly your repository hosts without talking to it...)?

Also, I've seen that you currently don't publish source and javadoc JARs.
If you do it becomes much easier for users to work with your library and contribute patches.

**Comment by sirthias** [comment]
btw: I [just added](https://github.com/sirthias/hetznercloud-java/commit/bebd89a287546a27bc2eeaaf6c683fd9ae19b793) an [SBT](https://www.scala-sbt.org/) build around your project and published to sonatype under my group-id (`com.decodified`). I will work with these artifacts until this ticket is closed...

**Comment by TomSDEVSN** [comment]
Hi Mathias,

thank you for your reply.

So I will upload the artifact to Maven central in the next few days (I'm currently very busy, because of school).

Best Regards
Tom

**Comment by sirthias** [comment]
Hi Tom,

unfortunately publishing to maven central via sonatype is a somewhat involved process to set up.
You first need to get a sonatype account, open a ticket to have the sonatype folks give you publishing rights for your group id, set up the various maven plugins to package and sign your artifacts, push them to sonatype, log in and "close" the publishing job before hitting the "release" button there.

But seeing what you've already accomplished here and how nicely structured your code is I'm sure this all will present no real problem for you.

Awesome job you did here!
We are using your library in production since yesterday and thing works really nicely so far.
Thank you for your work! 👍

**Comment by TomSDEVSN** [comment]
Hi Mathias,

I published hetznercloud-api after one year now to the sonatype central.
It'll take a few hours until it is available in Maven central.

I'm very sorry that I wasn't able to do that earlier.

Regards,
Tom
