### ISSUE TITLE
Import Loadbalancer from private repo

### ISSUE THREAD

**Issue by TomSDEVSN** [TomSDEVSN/hetznercloud-java#22]

**Comment by ZentornoLP** [comment]
I need that Loadbalancer for something i am working on at the moment is there any way you could import the load balancer so it can be used by everyone?

**Comment by TomSDEVSN** [comment]
> I need that Loadbalancer for something i am working on at the moment is there any way you could import the load balancer so it can be used by everyone?

I'll do a release tomorrow. There is still a bit work needed.

**Comment by TomSDEVSN** [comment]
Missed to do a release, I'm sorry. I would be able to do it on Monday or Tuesday, depending on how I can handle the time.

**Comment by TomSDEVSN** [comment]
@ZentornoLP Time was too fast, deployed it now and released with version 2.11.0 on prod.
