### ISSUE TITLE
Unify accessibility of model class fields

### ISSUE THREAD

**Issue by sirthias** [TomSDEVSN/hetznercloud-java#3]
Currently accessibility of model class fields is not consistent.

E.g. `Servers#servers`, `ResponseSSHKeys#sshKeys` and `ResponseServerTypes#serverTypes` are `private`, while `ResponseImages#images` and `ResponseISOS#isos` are `public`.

IMHO the library should pick one style and consistently use it across all types.

Additionally, and depending on the constraints of the serialization magic in use (that I am not familiar with), I would suggest that all data classes become as immutable as possible, i.e.:

- all data classes be marked `final`
- all data class fields be marked `final`
- all data class fields be marked `@NonNull` unless `null` is explicitly allowed by the API (e.g. for optional fields?)

**Comment by TomSDEVSN** [comment]
Hi Mathias,

thank you for your issue.

This is one point on my ToDo-List, to change the modifiers from `public` to `private`.
It will come with the next update.

Best Regards
Tom
