### ISSUE TITLE
Add DNS support

### ISSUE THREAD

**Issue by MrGraversen** [TomSDEVSN/hetznercloud-java#49]
Hello,

Really appreciate the work done with this project, thank you!!

A useful addition to this library would be if Hetzner DNS support was added. Documentation: https://dns.hetzner.com/api-docs

Do you accept PRs? Could be done in a fork and contributed back to this project, if you wish.

**Comment by TomSDEVSN** [comment]
Hi @MrGraversen,

thank you for the idea. Yes I accept PRs. But I think the DNS part should not be implemented in this project.

DNS is not a part or product of Hetzner Cloud, it is a separate project which also gets managed by an other department.

**Comment by MrGraversen** [comment]
OK, I understand your reasoning 😄
