### ISSUE TITLE
Align data model type names with Java convention

### ISSUE THREAD

**Issue by sirthias** [TomSDEVSN/hetznercloud-java#5]
Currently the request and response model types are named as `RequestXXX` and `ResponseXXX` which is not in line with Java naming conventions.

Usually type names end with the *basic* name and are prefixed with qualifiers.
E.g. a `ServerRequest` is a first and foremost a *request*. The prefix `Server` qualifies it and says that is a `Request` for a `Server`. The same logic applies to responses.

Therefore all the types should really be named the other way around, i.e. `XXXRequest` and `XXXResponse`.

**Comment by TomSDEVSN** [comment]
Hi Mathias,

first, I'm sorry for the late response.

I will **not** change the names of the Request / Response classes because that would make the whole API/Integration incompatible and the principle of "Semantic Versioning" is not available anymore.

Best Regards
Tom

**Comment by sirthias** [comment]
It's true that it'd be a breaking change that would require a major version jump.
Nevertheless it's definitely something that can be done within the semver principles.

I don't quite get what you mean by "make the whole API/Integration incompatible".
Do you mean the "breaking change"-type nature of this fix?

**Comment by TomSDEVSN** [comment]
Hi Mathias,

yes, I mean the "breaking change" of this fix.

**Comment by sirthias** [comment]
So why don't you simply change the version number to `2.0.0`?
Then it's absolutely clear that this version upgrade is breaking...

**Comment by TomSDEVSN** [comment]
Hi Mathias,

thank you for your reply.
So, I will change it in version 2.0.0

Best Regards
Tom
